# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  batch: 'false'
  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest
  # TODO - Remove after repository is made public
  name: 'Local pz'

steps:
- script: yarn install
- script: yarn build
- script: |
    cd dist
    zip -r package.zip *
    mv package.zip ../
    cd ..
- script: yarn e2e-deploy-infra
  env:
    AZURE_STORAGE_ACCOUNT_NAME: $(AZURE_STORAGE_ACCOUNT_NAME)
    AZURE_STORAGE_CONTAINER_NAME: $(AZURE_STORAGE_CONTAINER_NAME)
    AZURE_STORAGE_RESOURCE_GROUP: $(AZURE_STORAGE_RESOURCE_GROUP)
    AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
    FPJS_PRE_SHARED_SECRET: $(FPJS_PRE_SHARED_SECRET)
