pr: none
trigger:
  tags:
    include:
      - 'v*'

pool:
  vmImage: ubuntu-latest

variables:
  TAG: $[replace(variables['Build.SourceBranch'], 'refs/tags/', '')]

steps:
- script: echo $TAG
  displayName: 'Output tag'
  env:
    TAG: $(TAG)
- script: yarn install --ignore-engines && npx playwright install && yarn global add ts-node
  displayName: 'Install dependencies'
- script: ts-node scripts/downloadGithubReleasePackage.ts
  displayName: 'Download release artifact from GitHub'
  env:
    TAG: $(TAG)
- script: yarn build:example-website
  displayName: 'Build website'
  env:
    VITE_API_KEY: $(API_KEY)
    VITE_ENDPOINT: $(VITE_ENDPOINT)
    VITE_SCRIPT_URL_PATTERN: $(VITE_SCRIPT_URL_PATTERN)
    NODE_OPTIONS: "--max_old_space_size=16384"

- task: AzureCLI@2
  displayName: 'Deploy infrastructure'
  env:
    AZURE_STORAGE_ACCOUNT_NAME: $(AZURE_STORAGE_ACCOUNT_NAME)
    AZURE_STORAGE_CONTAINER_NAME: $(AZURE_STORAGE_CONTAINER_NAME)
    AZURE_STORAGE_RESOURCE_GROUP: $(AZURE_STORAGE_RESOURCE_GROUP)
    AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
    FPJS_PRE_SHARED_SECRET: $(FPJS_PRE_SHARED_SECRET)
  inputs:
    azureSubscription: 'azure-proxy-integration-e2e-tests'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'yarn e2e-deploy-infra'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-proxy-integration-e2e-tests'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'yarn test:e2e'
  displayName: 'Run e2e tests'
  env:
    CI: 'true'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-proxy-integration-e2e-tests'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'yarn e2e-destroy-infra'
  displayName: 'Destroy infrastructure'
  condition: always()
  env:
    AZURE_STORAGE_ACCOUNT_NAME: $(AZURE_STORAGE_ACCOUNT_NAME)
    AZURE_STORAGE_CONTAINER_NAME: $(AZURE_STORAGE_CONTAINER_NAME)
    AZURE_STORAGE_RESOURCE_GROUP: $(AZURE_STORAGE_RESOURCE_GROUP)
    AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
    FPJS_PRE_SHARED_SECRET: $(FPJS_PRE_SHARED_SECRET)
