name: 'Publish release'
description: 'Publishes release, if it is a release pull request'
inputs:
  token:
    description: 'The GitHub token'
    required: true
  tag:
    description: 'The tag to publish'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
